updated

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -20,7 +20,7 @@ jobs:
       - name: Build on EC2
         run: |
           ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
-            set -x  # Enable debug mode to trace commands
+            set -x  # Enable debug mode
             echo "Connected to EC2 for Build"
 
             # Install Git
@@ -121,7 +121,7 @@ jobs:
             # Build and tag images with version
             COMMIT_SHA=$(git rev-parse --short HEAD) || { echo "Failed to get commit SHA"; exit 1; }
             echo "Building services with tag: $COMMIT_SHA"
-            timeout 20m docker-compose --progress plain build --no-cache || { echo "Build timed out or failed"; exit 1; }
+            timeout 30m docker-compose build --no-cache > build.log 2>&1 || { echo "Build timed out or failed"; cat build.log; exit 1; }
             docker tag code2mdt-frontend:latest frontend:"$COMMIT_SHA"
             docker tag code2mdt-backend:latest backend:"$COMMIT_SHA"
             docker tag code2mdt-backend1:latest backend1:"$COMMIT_SHA"
